language: node_js
node_js:
- '0.10'
- '0.11'
deploy:
  provider: npm
  email: jeffrey.jagoda@gmail.com
  api_key:
    secure: PKYiGwjT03vK7bU8EGFDiC8MtU1w3ZqS+K+DrowWLXs3Hk9BbbLPOQ89PWrg5DfRTqqk8iYxMX+gFf+U/0OkhtklyW5VaU1VWeXQ3YSE95gcvpCLgGn7BgMdZaVRyublwCRULEhdOZSG7OoNxG2fBx4mQ75yTtG7KwJBoDO/Ywc=
  on:
    tags: true
    repo: jagoda/badge
    all_branches: true
